### ISSUE TITLE
MessageGroup.replaceMessage does not work as expected

### ISSUE THREAD

**Issue by victorchapado** [chatscope/use-chat#13]
Hi!
There is an error with the implementation of `MessageGroup.replaceMessage`. Right now, the first condition always returns false because the length of the array of messages is always greater than the index that we need to replace. Besides that, the concatenation preserves the original `messages` array so, this one increases each time that this method is called.

My code suggestion:

```
replaceMessage(message, index) { 
  if (this.messages.length <= index) {
    return false;
  }

  this.messages = this.messages.slice(0, index)
    .concat(message)
    .concat(this.messages.slice(index + 1));

  return true;
}
````

**Comment by supersnager** [comment]
@victorchapado Thank you for the report!
