### ISSUE TITLE
Use with React Native

### ISSUE THREAD

**Issue by iammeetpatel** [chatscope/use-chat#14]
Hello @kalabro @supersnager !

Can you please help me with how can I use `use-chat` with React native?

**Comment by supersnager** [comment]
@iammeetpatel Please describe your problem

**Comment by iammeetpatel** [comment]
I tried to set up the same as the example here https://github.com/chatscope/use-chat#basic-usage in React Native and run the app it didn't work.

**Comment by supersnager** [comment]
@iammeetpatel This example uses the web components [@chatscope/chat-ui-kit-react](https://github.com/chatscope/chat-ui-kit-react) (file Chat.js). If you want to use the use-chat library with React Native you need to use some RN components within the **&lt;ChatProvider/&gt;**.
