### ISSUE TITLE
The ChatService is re-constructed / re-render whenever there is state update

### ISSUE THREAD

**Issue by 15217035** [chatscope/use-chat#15]
### Expected Behavior
The ChatService is expected to initialize only once. The one would be used for all chats after the program launched. 

### Current Behavior
The ServiceFactory is placed outside of the component, so a single ServiceFactory constant is created. However, this function is executed more than once. It results in ChatService being re-constructed / re-render all the time.

### Steps to Reproduce
I copied the ExampleChatSerive and created one for myself to hook up with my own server. 
To try it, I think we can add a log to check out.
```
// Create serviceFactory
const serviceFactory = (storage, updateState) => {
  console.log("new ExampleChatService created");
  return new ExampleChatService(storage, updateState);
};
```

**Comment by 15217035** [comment]
Would anyone have a way to prevent it elegantly, please? 

I found a very ugly way.

**Comment by supersnager** [comment]
@15217035 Thank you for the report.
I found the BUG.
I'm working on it, so it should be fixed later today.

**Comment by 15217035** [comment]
Greatly helps! Thank you @supersnager 💯
