### ISSUE TITLE
ChatProvider getUser should change according to the storage change

### ISSUE THREAD

**Issue by Anberm** [chatscope/use-chat#2]
![image](https://user-images.githubusercontent.com/34148806/120414153-1760f500-c38c-11eb-9c54-2842c99445d2.png)

Similarly, other storage-dependent Callbacks should also change

**Comment by supersnager** [comment]
@Anberm Thank you for the PR. Why have you closed it? Imho this is a bug and should be fixed.

Please check my comment in the PR. I will gladly merge this PR if you will do some changes and reopen it.

**Comment by Anberm** [comment]
@supersnager Yes, this should be fixed. I also modified some codes according to actual needs in the process of using it. I will rearrange the PR after that.
