### ISSUE TITLE
Dynamically build Chat User List

### ISSUE THREAD

**Issue by ricco-douro** [chatscope/use-chat#8]
Hello, I wonder if you can help me:

I have dynamically built both chats and users, as you can see, mixing half harcoded users with data from my users table. However, when displaYing the chat (which is working, by the way) it only displays the users that are harcoded, and not the softcoded users.

I feel that i am very close, but I am in need of some help or pointers.

Could you help me?

![image](https://user-images.githubusercontent.com/46711848/155238542-a9d234c2-79b7-45c2-bf15-e1cb13e4df9b.png)

![image](https://user-images.githubusercontent.com/46711848/155238561-c02810f6-fd06-48e2-8558-5a617d8c80e1.png)

-------------------------------

import "bootstrap/dist/css/bootstrap.min.css";
import './InsideChat.css';
import "@chatscope/chat-ui-kit-styles/dist/default/styles.min.css";
import {
    BasicStorage,
    ChatMessage,
    ChatProvider,
    Conversation,
    ConversationId,
    ConversationRole,
    IStorage,
    MessageContentType,
    Participant,
    Presence,
    TypingUsersList,
    UpdateState,
    User,
    UserStatus
} from "@chatscope/use-chat";
import {ExampleChatService} from "@chatscope/use-chat/dist/examples";
import {Chat} from "./components/Chat";
import {nanoid} from "nanoid";
import {Col, Container, Row} from "react-bootstrap";
//import {akaneModel, ricModel, users} from "./data/data";
import {AutoDraft} from "@chatscope/use-chat/dist/enums/AutoDraft";
import {Footer} from "./components/Footer";
import { io } from "socket.io-client";
//import { users } from "./data/data";

var socket;
var endpoint:any =  process.env.REACT_APP_BACKEND_URL;
socket = io(endpoint);
let StorageArray:any=[];
let UserArray:any=[];
//let users:any=[];
let users: {name: string, avatar: string}[]

// sendMessage and addMessage methods can automagically generate id for messages and groups
// This allows you to omit doing this manually, but you need to provide a message generator
// The message id generator is a function that receives message and returns id for this message
// The group id generator is a function that returns string

const messageIdGenerator = (message: ChatMessage<MessageContentType>) => nanoid();
const groupIdGenerator = () => nanoid();

const akaneStorage = new BasicStorage({groupIdGenerator, messageIdGenerator});
const ricStorage = new BasicStorage({groupIdGenerator, messageIdGenerator});

const akane = new User({
    id: "akane",
    presence: new Presence({status: UserStatus.Available, description: ""}),
    firstName: "",
    lastName: "",
    username: "akane",
    email: "",
    avatar: "../assets/akane.svg",
    bio: ""
});

const ric = new User({
    id: "Ric",
    presence: new Presence({status: UserStatus.Available, description: ""}),
    firstName: "",
    lastName: "",
    username: "Ric",
    email: "",
    avatar: "../assets/ric.png",
    bio: ""
});

let chats = [
    {name: "Akane", storage: akaneStorage},
	{name: "Ric", storage: ricStorage}
];
    users = [
    {name: "Akane", avatar: "../assets/akane.svg"},
	{name: "Ric", avatar: "../assets/ric.png"}
];

let lUsers:any;

socket.emit("chatrequest", {'oper' : 'get_users'});
socket.on("chatresponse", function(getResponse:any) {
    lUsers=getResponse.users
    ProcessUsers(lUsers)
  });

  

const ProcessUsers = ((MyUsers:any) =>{
    MyUsers.forEach((item:any, index:any)=>{
        console.log("Index;",index, item)
    
        StorageArray[index] = new BasicStorage({groupIdGenerator, messageIdGenerator});
        UserArray[index] = new User({
            id: item.id,
            presence: new Presence({status: UserStatus.Available, description: ""}),
            firstName: "",
            lastName: "",
            username: item.name,
            email: "",
            avatar: `../assets/${item.id}.png`,
            bio: ""
        });

        let myname = item.name;

        chats.push({name: myname, storage: StorageArray[index]});
        users.push({name: myname, avatar:`../assets/${item.id}.png`})
    })

    console.log("chats", chats)
    console.log("users", users)

})

// Create serviceFactory
const serviceFactory = (storage: IStorage, updateState: UpdateState) => {
    return new ExampleChatService(storage, updateState);
};

function createConversation(id: ConversationId, name: string): Conversation {
    return new Conversation({
        id,
        participants: [
            new Participant({
                id: name,
                role: new ConversationRole([])
            })
        ],
        unreadCounter: 0,
        typingUsers: new TypingUsersList({items: []}),
        draft: ""
    });
}

// Add users and conversations to the states
chats.forEach(c => {

    users.forEach(u => {
		
        if (u.name !== c.name) {
            c.storage.addUser(new User({
                id: u.name,
                presence: new Presence({status: UserStatus.Available, description: ""}),
                firstName: "",
                lastName: "",
                username: u.name,
                email: "",
                avatar: u.avatar,
                bio: ""
            }));

            const conversationId = nanoid();

            const myConversation = c.storage.getState().conversations.find(cv => typeof cv.participants.find(p => p.id === u.name) !== "undefined");
            if (!myConversation) {

                c.storage.addConversation(createConversation(conversationId, u.name));

                const chat = chats.find(chat => chat.name === u.name);

                if (chat) {

                    const hisConversation = chat.storage.getState().conversations.find(cv => typeof cv.participants.find(p => p.id === c.name) !== "undefined");
                    if (!hisConversation) {
                        chat.storage.addConversation(createConversation(conversationId, c.name));
                    }

                }

            }

        }
    });

});

function InsideChat() {
/*
    return (
        <div className="h-30 d-flex flex-column overflow-hidden">
            <Container fluid className="p-4 flex-grow-1 position-relative overflow-hidden">
                <Row className="h-30 pb-2 flex-nowrap">
                    <Col>
                        <ChatProvider serviceFactory={serviceFactory} storage={ricStorage} config={{
                            typingThrottleTime: 250,
                            typingDebounceTime: 900,
                            debounceTyping: true,
                            autoDraft: AutoDraft.Save | AutoDraft.Restore
                        }}>
                            <Chat user={ric}/>
                        </ChatProvider>
                    </Col>
                </Row>
            </Container>
            
        </div>
    );
    */
    return (
        <div className="h-100 d-flex flex-column overflow-hidden">
        <Container fluid className="p-4 flex-grow-1 position-relative overflow-hidden">
            <Row className="h-50 pb-2 flex-nowrap overflow-hidden">
                <Col className="overflow-hidden"> 
                    <ChatProvider serviceFactory={serviceFactory} storage={ricStorage} config={{
                        typingThrottleTime: 250,
                        typingDebounceTime: 900,
                        debounceTyping: true,
                        autoDraft: AutoDraft.Save | AutoDraft.Restore
                    }}>
                        <Chat user={ric}/>
                    </ChatProvider>
                </Col>
            </Row>    
        </Container>
    </div>
    );
}

export default InsideChat;

**Comment by supersnager** [comment]
@ricco-douro Thank you for your question.

Your user list is not updating probably because a user should be added to the storage using 
```ts
storage.addUser(user:User),
```
method,  no to the user's array.

However, I'm afraid the problem lies elsewhere.

This code should work differently.

First of all socket.io code, connection, message sending, and message receiving should be implemented in your service, where **the service** is an equivalent of the ExampleChatService.

The next thing is, you do not need multiple storage instances. There should be only one storage instance per ChatProvider, not one instance per user.

I guess you were based on https://github.com/chatscope/use-chat-example, but... 
There are four users and four storages because there are also four chat "applications", You can treat each &lt;ChatProvider /&gt; in this example as a separate application. If you want to make a single chat app, you need only one &lt;ChatProvider /&gt; with one storage.

Please check the comments in the [ExampleChatService](https://github.com/chatscope/use-chat/blob/main/src/examples/ExampleChatService.ts) they can be helpful.

As a start point, you can copy-paste ExampleChatService class and implement your communication service based on it.

I hope this helps. I know, the documentation is still weak :), so feel free to ask more questions if something is not clear.
