### ISSUE TITLE
how to add history messages to chatStorage

### ISSUE THREAD

**Issue by ranglang** [chatscope/use-chat#9]
it would be neccessary for fetched more history messages from server

**Comment by supersnager** [comment]
@ranglang Thank's for the question.

The history should be fetched by the service e.g. by your custom **getHistory** method.

But there is no method in the storage to bulk add messages at the beginning of the collection.

Would such a function be suitable for you?
```js
 storage.addMessages(messages:Message[], conversationId: ConversationId, prepend?: bool)
```

**Comment by ranglang** [comment]
thanks to @supersnager  , yes ,  i notice that i can use a custom storage. thanks again

**Comment by Adwait-Fleapo** [comment]
@ranglang if possible can you share how you were able to insert the old messages into storage?
thanks

**Comment by adjiganoff** [comment]
@Adwait-Fleapo what I ended up doing is too simple, but seemingly working way:

1. Copy (not extend) BasicStorage [contents](https://github.com/chatscope/use-chat/blob/v3.1.2/src/BasicStorage.ts) into a separate file. Extending didn't work for me as the new method (`prependMessage`) I was going to add required access to private attributes which is [prohibited by type system](https://www.typescriptlang.org/docs/handbook/2/classes.html#private) when you extend some class.
2. Add `prependMessage` [method](https://pastebin.com/bhgfEeRE) which essentially is an `addMessage` method from BasicStorage but with some amendments which provide "prepending" logic.
3. Call `prependMessage` _in a loop_ at the point when history data chunks are coming from the API in your app.

@supersnager looks like adding a method that would prepend history data in batches seems a good idea.
Should I open a related issue or it's something that you're already considering adding in future releases?
